import React from "react";
import ReactDOM from "react-dom/client";
import Counter from "./chapter_07/Counter";
import Counter2 from "./chapter_07/Counter2";
import Counter3 from "./chapter_07/Counter3"
import Counter4 from "./chapter_07/Counter4";
import Counter5 from "./chapter_07/Counter5";
import Counter6 from "./chapter_07/Counter6";
import Counter7 from "./chapter_07/Counter7";
import Counter8 from "./chapter_07/Counter8";
import Counter9 from "./chapter_07/Counter9";
import Area from "./chapter_07/Area";
import Example from "./chapter_07/Example";
import MouseTracker from "./chapter_07/MouseTracker";
import Timer from "./chapter_07/Timer";
import FetchData from "./chapter_07/FetchData";
import Accommodate from "./chapter_07/Accommodate";
const root = document.getElementById("root");
ReactDOM.createRoot(root).render(<Accommodate />);
